services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Endroid\AdventureBundle\:
        resource: '../../*'

    Endroid\AdventureBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
