services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Endroid\AdventureBundle\:
        resource: '../../*'

    Endroid\AdventureBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

#    Endroid\AdventureBundle\Domain\Command\Handler\:
#        resource: '%kernel.project_dir%/vendor/endroid/adventure-bundle/src/Domain/Command/Handler/*'
#        tags:
#            - { name: messenger.message_handler, bus: messenger.bus.default }
